source 'https://github.com/CocoaPods/Specs.git'

use_modular_headers!
platform :ios, '10.0'

target 'XKRefreshExtension_Example' do
  pod 'XKRefreshExtension', :path => '../'

  target 'XKRefreshExtension_Tests' do
    inherit! :search_paths
  end
  
  
end
